version: "3"
services:
  node-app:
    build:
      context: ./node-app
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./node-app:/app
  react-app:
    depends_on:
      - node-app
    build:
      context: ./react-app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./react-app:/app
  
